export type TripDay={date:string;iso:string;place:string;route:string;km:number;time:string;sleep:string;detail:string;plan:string;coords:[number,number]};
export type Stay={id:string;city:string;dates:string;name:string;status:string;price:string;note:string;kind:string;website:string;contact:string;details:string;observations:string;whatsapp:string;email:string;instagram:string;address:string;mapsQuery:string;checkIn?:string;checkOut?:string;emailUrl?:string;accessInstructions?:string;restaurantMenu?:string};
export type Excursion={id:string;place:string;date:string;name:string;status:string;price:string;note:string;kind:string;website:string;whatsapp:string;email:string;instagram:string;address:string;details:string;observations:string};
export type Restaurant={id:string;city:string;name:string;style:string;moment:string;note:string;mapsQuery:string;instagram?:string;whatsapp?:string;status?:string;plannedDay?:string;rating?:number};
export type Expense={id:string;date:string;concept:string;category:string;amount:string;currency:"ARS"|"USD";paidBy:string;note:string};
export type Memory={id:string;day:string;place:string;author:string;caption:string;tag:string;imageUrl:string;createdAt:string;favorite:boolean};

export const seedDays:TripDay[]=[
["Día 1","2026-09-19","Chilecito","Córdoba → Chilecito",480,"7 h + paradas","Alojamiento Demo Norte","Inicio de la ruta y llegada tranquila.","Salida temprano\nParadas de descanso\nCheck-in\nPaseo al atardecer",[-29.165,-67.497]],
["Día 2","2026-09-20","Chilecito","Día local",35,"Flexible","Alojamiento Demo Norte","Día para explorar la ciudad.","Cable Carril\nSanta Florentina\nAlmuerzo regional",[-29.165,-67.497]],
["Día 3","2026-09-21","Villa Unión","Chilecito → Cuesta de Miranda → Villa Unión",125,"3 h + paradas","Hotel Demo Miranda","Ruta panorámica de montaña.","Nonogasta\nCuesta de Miranda\nCheck-in",[-29.315,-68.226]],
["Día 4","2026-09-22","Talampaya","Villa Unión ↔ Talampaya",110,"Día completo","Hotel Demo Miranda","Jornada en el parque nacional.","Salida temprano\nCircuito principal\nRegreso",[-29.786,-67.993]],
["Día 5","2026-09-23","Barreal","Villa Unión → Jáchal → Barreal",420,"6–7 h","Posada Demo Cordillera","Tramo rumbo a la Cordillera.","Salida\nCombustible\nJáchal\nBarreal",[-31.643,-69.475]],
["Día 6","2026-09-24","El Leoncito","Barreal ↔ El Leoncito",70,"Día tranquilo","Posada Demo Cordillera","Naturaleza y aire libre.","Pampa El Leoncito\nParque nacional\nAtardecer",[-31.798,-69.295]],
["Día 7","2026-09-25","Valle Fértil","Barreal → Valle Fértil",430,"6–7 h","Hostería Demo Valle","Ruta de paisajes sanjuaninos.","Ruta Interlagos\nAlmuerzo\nLlegada",[-30.633,-67.468]],
["Día 8","2026-09-26","Valle de la Luna","Valle Fértil → Ischigualasto",100,"Día + noche","Hospedaje Demo Luna","Circuito diurno y nocturno.","Circuito diurno\nDescanso\nCircuito nocturno",[-30.116,-67.9]],
["Día 9","2026-09-27","Córdoba","San Juan → Córdoba",600,"8 h + paradas","Casa","Regreso y cierre.","Salida\nParadas\nLlegada",[-31.4201,-64.1888]],
].map(([date,iso,place,route,km,time,sleep,detail,plan,coords])=>({date,iso,place,route,km,time,sleep,detail,plan,coords} as TripDay));

const stay=(id:string,city:string,name:string,status:string,price:string,kind:string):Stay=>({id,city,dates:"Estadía demostrativa",name,status,price,note:"Datos ilustrativos",kind,website:"",contact:"Contacto de ejemplo",details:"Habitación doble",observations:"Información ficticia para portfolio.",whatsapp:"",email:"",instagram:"",address:city,mapsQuery:city});
export const seedStays:Stay[]=[stay("norte","Chilecito","Alojamiento Demo Norte","Confirmado","$120.000","ok"),stay("miranda","Villa Unión","Hotel Demo Miranda","Reservado","$180.000","ok"),stay("cordillera","Barreal","Posada Demo Cordillera","Pendiente","$210.000","pending"),stay("valle","Valle Fértil","Hostería Demo Valle","Disponible","$95.000","quote"),stay("luna","Ischigualasto","Hospedaje Demo Luna","Pendiente","A definir","pending")];
export const seedExcursions:Excursion[]=[{id:"talampaya",place:"Talampaya",date:"Día 4",name:"Circuito Talampaya",status:"Pendiente",price:"A definir",note:"Demostración",kind:"tour",website:"https://talampaya.com/planea-tu-visita/",whatsapp:"",email:"",instagram:"",address:"Parque Nacional Talampaya",details:"Opción de mañana.",observations:"Confirmar horario."},{id:"ischigualasto",place:"Ischigualasto",date:"Día 8",name:"Circuito de Luna Llena",status:"Prioridad",price:"A definir",note:"Sujeto al clima",kind:"moon",website:"https://www.ischigualasto.gob.ar/",whatsapp:"",email:"",instagram:"",address:"Parque Provincial Ischigualasto",details:"Reserva previa.",observations:"Confirmar fecha."}];
export const seedRestaurants:Restaurant[]=[{id:"r1",city:"Chilecito",name:"Cocina Regional Demo",style:"Riojana",moment:"Almuerzo",note:"Opción ilustrativa.",mapsQuery:"Chilecito, La Rioja",status:"Alternativa"},{id:"r2",city:"Villa Unión",name:"Bodegón Demo",style:"Regional",moment:"Cena",note:"Opción ilustrativa.",mapsQuery:"Villa Unión, La Rioja",status:"Queremos ir"},{id:"r3",city:"Barreal",name:"Restaurante Cordillera Demo",style:"Argentina",moment:"Cena",note:"Opción ilustrativa.",mapsQuery:"Barreal, San Juan",status:"Alternativa"}];
export const seedExpenses:Expense[]=[{id:"demo",date:"2026-08-01",concept:"Reserva de alojamiento (demo)",category:"Alojamiento",amount:"120000",currency:"ARS",paidBy:"Viajero 1",note:"Dato ilustrativo"}];
