"use client";

import { useEffect, useMemo, useState } from "react";
import TripMap from "./TripMap";
import { seedDays,seedStays,seedExcursions,seedRestaurants,seedExpenses,type TripDay,type Stay,type Excursion,type Restaurant,type Expense,type Memory } from "./trip-data";

type Tab="today"|"route"|"plan"|"expenses"|"memories";
type PlanSection="stays"|"tours"|"food"|"ready";
type Weather={temperature:number;code:number;wind:number}|null;
const DATA_VERSION=21;
const taskNames=["Reservar circuito de Talampaya","Confirmar alojamiento en Barreal","Resolver alojamiento en Valle Fértil","Resolver última noche","Reservar circuito de luna llena","Revisar el vehículo","Descargar mapas sin conexión"];
const confirmed=(s:Stay)=>/confirmado|reservado|elegido/i.test(s.status);
const maps=(q:string)=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;
const directions=(a:string,b:string)=>`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(a)}&destination=${encodeURIComponent(b)}&travelmode=driving`;
const money=(n:number)=>n.toLocaleString("es-AR");
const weatherText=(code:number)=>code===0?"Despejado":code<4?"Parcialmente nublado":code<60?"Nublado":code<80?"Lluvia":"Tormentas";
type FuelStop={place:string;note:string;query:string};
const fuelStops:Record<string,FuelStop[]>={
 "2026-09-19":[{place:"Córdoba",note:"Salir con el tanque completo",query:"estaciones de servicio Córdoba Argentina"},{place:"Chamical",note:"Carga principal y descanso",query:"estaciones de servicio Chamical La Rioja"},{place:"Patquía",note:"Alternativa antes de Chilecito",query:"estaciones de servicio Patquía La Rioja"}],
 "2026-09-20":[{place:"Chilecito",note:"Completar antes del paseo local",query:"estaciones de servicio Chilecito La Rioja"}],
 "2026-09-21":[{place:"Chilecito",note:"Cargar antes de Cuesta de Miranda",query:"estaciones de servicio Chilecito La Rioja"},{place:"Villa Unión",note:"Completar al llegar",query:"estaciones de servicio Villa Unión La Rioja"}],
 "2026-09-22":[{place:"Villa Unión",note:"Salir lleno: no depender de servicios en el parque",query:"estaciones de servicio Villa Unión La Rioja"}],
 "2026-09-23":[{place:"Villa Unión",note:"Carga obligatoria antes del tramo largo",query:"estaciones de servicio Villa Unión La Rioja"},{place:"San José de Jáchal",note:"Parada principal de combustible",query:"estaciones de servicio San José de Jáchal San Juan"},{place:"Calingasta",note:"Completar antes de Barreal",query:"estaciones de servicio Calingasta San Juan"}],
 "2026-09-24":[{place:"Barreal",note:"Completar antes de El Leoncito",query:"estaciones de servicio Barreal San Juan"}],
 "2026-09-25":[{place:"Barreal",note:"Salir con tanque completo",query:"estaciones de servicio Barreal San Juan"},{place:"San Juan",note:"Carga principal del tramo",query:"estaciones de servicio San Juan Capital"},{place:"Caucete",note:"Último respaldo antes de Valle Fértil",query:"estaciones de servicio Caucete San Juan"}],
 "2026-09-26":[{place:"San Agustín de Valle Fértil",note:"Carga obligatoria antes de Ischigualasto",query:"estaciones de servicio San Agustín de Valle Fértil"}],
 "2026-09-27":[{place:"Patquía",note:"Primera carga del regreso",query:"estaciones de servicio Patquía La Rioja"},{place:"Chamical",note:"Carga principal y descanso",query:"estaciones de servicio Chamical La Rioja"},{place:"Serrezuela",note:"Respaldo antes de Córdoba",query:"estaciones de servicio Serrezuela Córdoba"}],
};

export default function V3(){
 const [tab,setTab]=useState<Tab>("today"); const [planSection,setPlanSection]=useState<PlanSection>("stays");
 const [days,setDays]=useState<TripDay[]>(seedDays); const [stays,setStays]=useState<Stay[]>(seedStays); const [excursions,setExcursions]=useState<Excursion[]>(seedExcursions); const [restaurants,setRestaurants]=useState<Restaurant[]>(seedRestaurants);
 const [expenses,setExpenses]=useState<Expense[]>(seedExpenses); const [memories,setMemories]=useState<Memory[]>([]); const [done,setDone]=useState<boolean[]>(Array(taskNames.length).fill(false)); const [budget,setBudget]=useState("2500000");
 const [editCode,setEditCode]=useState(""); const [ready,setReady]=useState(false); const [sync,setSync]=useState("Conectando…"); const [selectedDay,setSelectedDay]=useState(0); const [editingDay,setEditingDay]=useState(false); const [mapView,setMapView]=useState(false);
 const [selectedStay,setSelectedStay]=useState<Stay|null>(null); const [editingStay,setEditingStay]=useState(false); const [collapsed,setCollapsed]=useState<Record<string,boolean>>({}); const [undo,setUndo]=useState<{item:Stay;timer:number}|null>(null);
 const [weather,setWeather]=useState<Weather>(null); const [expenseForm,setExpenseForm]=useState({date:"2026-09-19",concept:"",category:"Comidas",amount:"",currency:"ARS" as "ARS"|"USD",paidBy:"Viajero 1",note:""});
 const [memoryForm,setMemoryForm]=useState({day:"Día 1",place:"Chilecito",author:"Viajero 1",caption:"",tag:"Paisaje"}); const [memoryFile,setMemoryFile]=useState<File|null>(null); const [uploading,setUploading]=useState(false);

 const now=new Date(); const start=new Date("2026-09-19T00:00:00-03:00"); const end=new Date("2026-09-28T00:00:00-03:00"); const phase=now<start?"planning":now>=end?"memory":"travel";
 const todayIndex=phase==="travel"?Math.max(0,Math.min(8,Math.floor((now.getTime()-start.getTime())/86400000))):phase==="memory"?8:0; const today=days[todayIndex];
 const totals=useMemo(()=>({ARS:expenses.filter(e=>e.currency==="ARS").reduce((a,e)=>a+Number(e.amount||0),0),USD:expenses.filter(e=>e.currency==="USD").reduce((a,e)=>a+Number(e.amount||0),0)}),[expenses]);
 const groups=useMemo(()=>Object.entries(stays.reduce<Record<string,Stay[]>>((a,s)=>{(a[s.city]??=[]).push(s);return a},{})).sort(([,a],[,b])=>(Number(a[0].dates.match(/\d+/)?.[0])||99)-(Number(b[0].dates.match(/\d+/)?.[0])||99)),[stays]);
 const confirmedCount=stays.filter(confirmed).length; const unresolved=["Barreal","Valle Fértil","Los Baldecitos"].filter(city=>!stays.some(s=>s.city===city&&confirmed(s)));
 const nextAction=unresolved[0]?`Elegir alojamiento en ${unresolved[0]}`:excursions.find(e=>/pendiente/i.test(e.status))?.name||"Todo importante está resuelto";

 useEffect(()=>{const code=sessionStorage.getItem("ruta-luna-edit-code")||"";setEditCode(code);try{const local=JSON.parse(localStorage.getItem("ruta-luna-v3")||"null");if(local){setDays(mergeDays(local.tripDays));setStays(local.stays??seedStays);setExcursions(local.excursions??seedExcursions);setRestaurants(local.restaurants??seedRestaurants);setExpenses(local.expenses??seedExpenses);setMemories(local.memories??[]);setDone(local.done??done);setBudget(local.budget??budget)}}catch{}fetch("/api/trip").then(r=>r.ok?r.json():Promise.reject()).then(data=>{const s=data.state;if(s){setDays(mergeDays(s.tripDays));setStays(mergeStays(s.stays,s.dataVersion??0));setExcursions(s.excursions??seedExcursions);setRestaurants(s.restaurants??seedRestaurants);setExpenses(s.expenses??seedExpenses);setMemories(s.memories??[]);setDone(s.done??done);setBudget(s.budget??budget)}setReady(true);setSync("Sincronizado")}).catch(()=>{setReady(true);setSync("Disponible sin conexión")});navigator.serviceWorker?.register("/sw.js?v=4").catch(()=>{});},[]);
 useEffect(()=>{if(!ready||!editCode)return;const state={dataVersion:DATA_VERSION,tripDays:days,stays,excursions,restaurants,expenses,memories,done,budget};localStorage.setItem("ruta-luna-v3",JSON.stringify(state));setSync("Guardando…");const t=window.setTimeout(()=>fetch("/api/trip",{method:"PUT",headers:{"content-type":"application/json","x-edit-code":editCode},body:JSON.stringify(state)}).then(r=>r.ok?setSync("Sincronizado"):setSync("No se pudo guardar")).catch(()=>setSync("Se guardará al recuperar señal")),800);return()=>clearTimeout(t)},[days,stays,excursions,restaurants,expenses,memories,done,budget,ready,editCode]);
 useEffect(()=>{const d=days[phase==="travel"?todayIndex:selectedDay];fetch(`https://api.open-meteo.com/v1/forecast?latitude=${d.coords[0]}&longitude=${d.coords[1]}&current=temperature_2m,weather_code,wind_speed_10m&timezone=America%2FArgentina%2FCordoba`).then(r=>r.json()).then(x=>setWeather({temperature:Math.round(x.current.temperature_2m),code:x.current.weather_code,wind:Math.round(x.current.wind_speed_10m)})).catch(()=>setWeather(null))},[selectedDay,phase,todayIndex,days]);

 function mergeStays(value:unknown,version:number){if(!Array.isArray(value))return seedStays;const list=(value as Stay[]).map(s=>({...seedStays.find(x=>x.id===s.id),...s} as Stay));if(version<DATA_VERSION){for(const s of seedStays)if(!list.some(x=>x.id===s.id))list.push(s);const master=seedStays.find(x=>x.id==="san-eduardo")!;for(let i=0;i<list.length;i++){if(list[i].id==="san-eduardo")list[i]={...list[i],...master};if(list[i].city==="Barreal")list[i]={...list[i],status:list[i].id==="san-eduardo"?"Elegido · Pendiente de reserva":"Alternativa",kind:list[i].id==="san-eduardo"?"ok":"pending"}}}return list}
 function mergeDays(value:unknown){if(!Array.isArray(value)||!value.length)return seedDays;return seedDays.map((seed,index)=>({...seed,...((value as Partial<TripDay>[])[index]||{})}))}
 async function unlock(){const code=prompt("Clave privada de edición");if(!code)return;const r=await fetch("/api/unlock",{method:"POST",headers:{"x-edit-code":code}});if(r.ok){setEditCode(code);sessionStorage.setItem("ruta-luna-edit-code",code);setSync("Edición activa")}else alert("Clave incorrecta")}
 function chooseStay(stay:Stay){if(!editCode)return unlock();setStays(v=>v.map(s=>s.city===stay.city?{...s,status:s.id===stay.id?"Confirmado":"Alternativa",kind:s.id===stay.id?"ok":"pending"}:s));setSelectedStay(null)}
 function updateSelectedStay(field:keyof Stay,value:string){if(!selectedStay)return;const next={...selectedStay,[field]:value};setSelectedStay(next);setStays(v=>v.map(s=>s.id===next.id?next:s))}
 function deleteStay(stay:Stay){if(!editCode)return; if(!confirm(`¿Archivar ${stay.name}? Podrás deshacerlo.`))return;setStays(v=>v.filter(s=>s.id!==stay.id));const timer=window.setTimeout(()=>setUndo(null),6000);setUndo({item:stay,timer})}
 function undoDelete(){if(!undo)return;clearTimeout(undo.timer);setStays(v=>[...v,undo.item]);setUndo(null)}
 function addExpense(){if(!editCode)return unlock();if(!expenseForm.concept||!expenseForm.amount)return;setExpenses(v=>[{...expenseForm,id:crypto.randomUUID()},...v]);setExpenseForm({...expenseForm,concept:"",amount:"",note:""})}
 async function addMemory(){if(!editCode)return unlock();if(!memoryFile)return alert("Elegí o sacá una foto");setUploading(true);const body=new FormData();body.append("photo",memoryFile);const r=await fetch("/api/photos",{method:"POST",headers:{"x-edit-code":editCode},body});if(r.ok){const u=await r.json();setMemories(v=>[{id:crypto.randomUUID(),...memoryForm,imageUrl:u.url,createdAt:new Date().toISOString(),favorite:false},...v]);setMemoryFile(null);setMemoryForm({...memoryForm,caption:""})}setUploading(false)}
 const currentStay=(city:string)=>stays.find(s=>s.city===city&&confirmed(s)); const tonight=currentStay(today.place)||currentStay(today.place==="Talampaya"?"Villa Unión":today.place==="El Leoncito"?"Barreal":today.place==="Valle de la Luna"?"Los Baldecitos":"");

 return <main className="v3">
  <header className="v3bar"><button className="v3brand" onClick={()=>setTab("today")}><img src="/icon.svg" alt=""/><span>RUTA DE LA LUNA</span></button><nav>{([['today','Hoy'],['route','Ruta'],['plan','Planificar'],['expenses','Gastos'],['memories','Recuerdos']] as [Tab,string][]).map(([k,l])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{l}</button>)}</nav><button className={`mode-pill ${editCode?'on':''}`} onClick={editCode?()=>{sessionStorage.removeItem("ruta-luna-edit-code");setEditCode("")}:unlock}>{editCode?"Edición activa":"Solo lectura"}</button></header>

  {tab==="today"&&<Today phase={phase} today={today} weather={weather} daysLeft={Math.max(0,Math.ceil((start.getTime()-now.getTime())/86400000))} confirmedCount={confirmedCount} unresolved={unresolved} nextAction={nextAction} totals={totals} tonight={tonight} onGo={(t)=>setTab(t)} onPlan={()=>{setPlanSection("stays");setTab("plan")}}/>}

  {tab==="route"&&<section className="v3page"><PageHead eyebrow="EL CAMINO" title="Hoja de ruta" copy="Agenda, hospedaje y combustible en una sola vista."/><div className="view-switch"><button className={!mapView?"active":""} onClick={()=>setMapView(false)}>Día por día</button><button className={mapView?"active":""} onClick={()=>setMapView(true)}>Mapa completo</button></div>{mapView?<TripMap stays={stays}/>:<div className="route-v3"><div className="day-list">{days.map((d,i)=><button key={d.iso} className={selectedDay===i?"active":""} onClick={()=>setSelectedDay(i)}><span>{i+1}</span><b>{d.date} · {d.place}</b><small>{d.route}</small></button>)}</div><article className="day-focus"><div className="focus-head"><p>DÍA {selectedDay+1} · {days[selectedDay].date}</p>{editCode&&<button onClick={()=>setEditingDay(!editingDay)}>{editingDay?"Cerrar":"Editar día"}</button>}</div>{editingDay?<div className="day-edit"><label>Destino<input value={days[selectedDay].place} onChange={e=>setDays(v=>v.map((d,i)=>i===selectedDay?{...d,place:e.target.value}:d))}/></label><label>Resumen<textarea value={days[selectedDay].detail} onChange={e=>setDays(v=>v.map((d,i)=>i===selectedDay?{...d,detail:e.target.value}:d))}/></label><label>Agenda<textarea rows={10} value={days[selectedDay].plan} onChange={e=>setDays(v=>v.map((d,i)=>i===selectedDay?{...d,plan:e.target.value}:d))}/></label></div>:<><h2>{days[selectedDay].place}</h2><p>{days[selectedDay].detail}</p><div className="focus-meta"><span>{days[selectedDay].km} km</span><span>{days[selectedDay].time}</span><button className="stay-jump" onClick={()=>{const stay=resolvedStay(days[selectedDay],stays);setPlanSection("stays");setTab("plan");if(stay)setSelectedStay(stay)}}>⌂ {resolvedSleep(days[selectedDay],stays)} →</button></div><ol>{days[selectedDay].plan.split("\n").map((p,i)=><li key={i}>{p}</li>)}</ol><section className="fuel-panel"><div className="fuel-title"><span>⛽</span><div><b>Combustible</b><small>Puntos recomendados para este día</small></div></div><div className="fuel-list">{(fuelStops[days[selectedDay].iso]||[]).map(stop=><a key={stop.place} href={maps(stop.query)} target="_blank"><div><b>{stop.place}</b><small>{stop.note}</small></div><span>Mapa ↗</span></a>)}</div></section><a className="action-link" href={directions(selectedDay?days[selectedDay-1].place:"Córdoba",currentStay(days[selectedDay].place)?.mapsQuery||days[selectedDay].place)} target="_blank">Abrir navegación →</a></>}</article></div>}</section>}

  {tab==="plan"&&<section className="v3page"><PageHead eyebrow="ANTES DE SALIR" title="Planificar" copy="Decisiones, reservas y preparativos en un solo lugar."/><div className="plan-tabs">{([['stays','Alojamientos'],['tours','Excursiones'],['food','Comer'],['ready','Preparar']] as [PlanSection,string][]).map(([k,l])=><button key={k} className={planSection===k?"active":""} onClick={()=>setPlanSection(k)}>{l}</button>)}</div>
   {planSection==="stays"&&<div className="stay-groups">{groups.map(([city,list])=>{const chosen=list.find(confirmed);const alternatives=list.filter(x=>x!==chosen);return <section className="stay-group" key={city}><div className="group-title"><div><p>{list[0].dates}</p><h2>{city}</h2></div><span className={chosen?"resolved":"pending"}>{chosen?"Resuelto":"Por decidir"}</span></div>{chosen&&<StayHero stay={chosen} onOpen={()=>setSelectedStay(chosen)}/>}<button className="alternatives-toggle" onClick={()=>setCollapsed(v=>({...v,[city]:!v[city]}))}>{chosen?`${alternatives.length} alternativas`:`Comparar ${list.length} opciones`} {collapsed[city]?"▴":"▾"}</button>{(collapsed[city]||!chosen)&&<div className="compare-wrap"><div className="compare-head"><span>Alojamiento</span><span>Precio</span><span>Servicios</span><span></span></div>{(chosen?alternatives:list).map(s=><div className="compare-row" key={s.id} onClick={()=>setSelectedStay(s)}><b>{s.name}<small>{s.status}</small></b><strong>{s.price}</strong><span>{s.note}</span>{editCode?<button onClick={e=>{e.stopPropagation();chooseStay(s)}}>Elegir</button>:<i>Ver →</i>}</div>)}</div>}</section>})}</div>}
   {planSection==="tours"&&<div className="card-grid">{excursions.map(e=><article className="plan-card tour-card" key={e.id}><p>{e.place} · {e.date}</p><h3>{e.name}</h3><b>{e.status}</b><span>{e.note}</span><div><a href={e.website||maps(e.address)} target="_blank">Información ↗</a>{editCode&&<select value={e.status} onChange={x=>setExcursions(v=>v.map(y=>y.id===e.id?{...y,status:x.target.value}:y))}><option>Pendiente de reservar</option><option>Reservado</option><option>Realizado</option><option>Descartado</option></select>}</div></article>)}</div>}
   {planSection==="food"&&<Food restaurants={restaurants} editable={!!editCode} setRestaurants={setRestaurants}/>} 
   {planSection==="ready"&&<div className="ready-grid"><section className="tasks"><h2>Prioridades</h2>{taskNames.map((t,i)=><label key={t} className={done[i]?"done":""}><input type="checkbox" disabled={!editCode} checked={done[i]} onChange={()=>setDone(v=>v.map((x,j)=>j===i?!x:x))}/><span>{t}</span></label>)}</section><aside className="readiness"><small>PREPARACIÓN</small><strong>{Math.round(done.filter(Boolean).length/taskNames.length*100)}%</strong><p>{nextAction}</p><button onClick={()=>{setPlanSection("stays")}}>Resolver siguiente →</button></aside></div>}
  </section>}

  {tab==="expenses"&&<section className="v3page"><PageHead eyebrow="CUENTAS DEL VIAJE" title="Gastos" copy="Presupuesto, pagos y quién abonó cada cosa."/><div className="money-summary"><article><small>Presupuesto</small><strong>$ {money(Number(budget))}</strong>{editCode&&<input value={budget} onChange={e=>setBudget(e.target.value.replace(/\D/g,""))}/>}</article><article><small>Gastado ARS</small><strong>$ {money(totals.ARS)}</strong></article><article><small>Disponible</small><strong>$ {money(Number(budget)-totals.ARS)}</strong></article><article><small>Gastado USD</small><strong>USD {money(totals.USD)}</strong></article></div><div className="expense-v3"><div className="expense-table">{expenses.map(e=><article key={e.id}><div><small>{e.date.split("-").reverse().join("/")} · {e.category}</small><b>{e.concept}</b><p>{e.paidBy}{e.note&&` · ${e.note}`}</p></div><strong>{e.currency==="ARS"?"$":"USD"} {money(Number(e.amount))}</strong>{editCode&&<button onClick={()=>setExpenses(v=>v.filter(x=>x.id!==e.id))}>Eliminar</button>}</article>)}</div>{editCode?<aside className="quick-form"><h3>Nuevo gasto</h3><input type="date" value={expenseForm.date} onChange={e=>setExpenseForm({...expenseForm,date:e.target.value})}/><input placeholder="Concepto" value={expenseForm.concept} onChange={e=>setExpenseForm({...expenseForm,concept:e.target.value})}/><div><select value={expenseForm.category} onChange={e=>setExpenseForm({...expenseForm,category:e.target.value})}>{["Alojamiento","Comidas","Combustible","Excursiones","Peajes","Compras","Otros"].map(x=><option key={x}>{x}</option>)}</select><select value={expenseForm.paidBy} onChange={e=>setExpenseForm({...expenseForm,paidBy:e.target.value})}><option>Viajero 1</option><option>Viajero 2</option><option>Ambos</option></select></div><div><select value={expenseForm.currency} onChange={e=>setExpenseForm({...expenseForm,currency:e.target.value as "ARS"|"USD"})}><option>ARS</option><option>USD</option></select><input inputMode="decimal" placeholder="Importe" value={expenseForm.amount} onChange={e=>setExpenseForm({...expenseForm,amount:e.target.value.replace(/[^0-9.]/g,"")})}/></div><input placeholder="Observación" value={expenseForm.note} onChange={e=>setExpenseForm({...expenseForm,note:e.target.value})}/><button onClick={addExpense}>Agregar gasto</button></aside>:<aside className="locked-box"><span>🔒</span><h3>Modo lectura</h3><p>Ingresá la clave para cargar gastos.</p><button onClick={unlock}>Habilitar edición</button></aside>}</div></section>}

  {tab==="memories"&&<section className="v3page"><PageHead eyebrow="NUESTRO VIAJE" title={phase==="memory"?"La historia que vivimos":"Recuerdos"} copy="Fotos, lugares y pequeñas historias compartidas."/><div className="memory-stats"><span>{memories.length} recuerdos</span><span>{memories.filter(m=>m.favorite).length} favoritos</span><span>{new Set(memories.map(m=>m.place)).size} lugares</span></div><div className="memory-layout">{editCode&&<aside className="memory-add"><h3>Guardar momento</h3><label className="photo-drop"><input type="file" accept="image/*" capture="environment" onChange={e=>setMemoryFile(e.target.files?.[0]||null)}/>{memoryFile?memoryFile.name:"Sacar foto o elegir de la galería"}</label><select value={memoryForm.day} onChange={e=>setMemoryForm({...memoryForm,day:e.target.value})}>{days.map(d=><option key={d.iso}>{d.date}</option>)}</select><input value={memoryForm.place} onChange={e=>setMemoryForm({...memoryForm,place:e.target.value})} placeholder="Lugar"/><textarea value={memoryForm.caption} onChange={e=>setMemoryForm({...memoryForm,caption:e.target.value})} placeholder="¿Qué quieren recordar?"/><select value={memoryForm.author} onChange={e=>setMemoryForm({...memoryForm,author:e.target.value})}><option>Viajero 1</option><option>Viajero 2</option><option>Ambos</option></select><button disabled={uploading} onClick={addMemory}>{uploading?"Guardando…":"Agregar recuerdo"}</button></aside>}<div className="gallery-v3">{memories.length?memories.map(m=><article key={m.id}><div><img src={m.imageUrl} alt={m.caption}/>{editCode&&<button onClick={()=>setMemories(v=>v.map(x=>x.id===m.id?{...x,favorite:!x.favorite}:x))}>{m.favorite?"★":"☆"}</button>}</div><p>{m.day} · {m.place}</p><h3>{m.caption||"Un momento para recordar"}</h3><small>{m.author}</small></article>):<div className="empty-story"><span>☾</span><h2>La historia empieza en septiembre</h2><p>Durante el viaje, cada foto va a transformar esta sección en un álbum cronológico.</p></div>}</div></div></section>}

  {selectedStay&&<div className="v3modal-bg" onClick={()=>{setSelectedStay(null);setEditingStay(false)}}><section className="v3modal" onClick={e=>e.stopPropagation()}><button className="x" onClick={()=>{setSelectedStay(null);setEditingStay(false)}}>×</button><p>{selectedStay.city} · {selectedStay.dates}</p><h2>{selectedStay.name}</h2>{editingStay?<div className="stay-edit-form">{([['price','Precio'],['note','Resumen'],['checkIn','Check-in'],['checkOut','Check-out'],['details','Servicios'],['observations','Condiciones'],['accessInstructions','Cómo llegar'],['restaurantMenu','Menú del restorán'],['whatsapp','WhatsApp'],['instagram','Instagram'],['website','Web'],['mapsQuery','Ubicación para el mapa']] as [keyof Stay,string][]).map(([field,label])=><label key={field}>{label}{['details','observations','accessInstructions','restaurantMenu'].includes(field)?<textarea rows={field==='restaurantMenu'?12:4} value={String(selectedStay[field]||'')} onChange={e=>updateSelectedStay(field,e.target.value)}/>:<input value={String(selectedStay[field]||'')} onChange={e=>updateSelectedStay(field,e.target.value)}/>}</label>)}<button className="save-stay" onClick={()=>setEditingStay(false)}>Guardar información</button></div>:<><div className="modal-summary"><strong>{selectedStay.price}</strong><span>{selectedStay.status}</span></div><dl><div><dt>Check-in</dt><dd>{selectedStay.checkIn||"A confirmar"}</dd></div><div><dt>Check-out</dt><dd>{selectedStay.checkOut||"A confirmar"}</dd></div><div><dt>Servicios</dt><dd>{selectedStay.details}</dd></div><div><dt>Condiciones</dt><dd>{selectedStay.observations}</dd></div>{selectedStay.accessInstructions&&<div className="access-alert"><dt>Importante · Cómo ingresar</dt><dd>{selectedStay.accessInstructions}</dd></div>}{selectedStay.restaurantMenu&&<div><dt>Menú del restorán</dt><dd className="menu-copy">{selectedStay.restaurantMenu}</dd></div>}</dl><div className="modal-links">{selectedStay.whatsapp&&<a href={`https://wa.me/${selectedStay.whatsapp}`} target="_blank">WhatsApp</a>}{selectedStay.instagram&&<a href={selectedStay.instagram} target="_blank">Instagram</a>}{selectedStay.website&&<a href={selectedStay.website} target="_blank">Web</a>}<a href={maps(selectedStay.mapsQuery)} target="_blank">Ubicación</a></div></>}{editCode&&!editingStay&&<div className="modal-edit"><button onClick={()=>setEditingStay(true)}>Editar información</button>{!confirmed(selectedStay)&&<button onClick={()=>chooseStay(selectedStay)}>Elegir alojamiento</button>}<button className="danger" onClick={()=>deleteStay(selectedStay)}>Archivar opción</button></div>}</section></div>}
  {undo&&<div className="undo-toast"><span>{undo.item.name} archivado</span><button onClick={undoDelete}>Deshacer</button></div>}
  <footer className="v3footer"><span>☾</span><p>Ruta de la Luna · Proyecto demostrativo</p><small>{sync} · Portfolio 2026</small></footer>
 </main>
}

function stayCity(day:TripDay){return day.place==="Talampaya"?"Villa Unión":day.place==="El Leoncito"?"Barreal":day.place==="Valle de la Luna"?"Los Baldecitos":day.place}
function resolvedStay(day:TripDay,stays:Stay[]){return stays.find(s=>s.city===stayCity(day)&&confirmed(s))}
function resolvedSleep(day:TripDay,stays:Stay[]){return resolvedStay(day,stays)?.name||day.sleep}
function PageHead({eyebrow,title,copy}:{eyebrow:string;title:string;copy:string}){return <div className="v3head"><p>{eyebrow}</p><h1>{title}</h1><span>{copy}</span></div>}
function StayHero({stay,onOpen}:{stay:Stay;onOpen:()=>void}){return <button className="stay-hero" onClick={onOpen}><div><small>ALOJAMIENTO ELEGIDO</small><h3>{stay.name}</h3><p>{stay.note}</p></div><div><strong>{stay.price}</strong><span>{stay.checkIn} → {stay.checkOut}</span><i>Ver reserva →</i></div></button>}
function Today({phase,today,weather,daysLeft,confirmedCount,unresolved,nextAction,totals,tonight,onGo,onPlan}:{phase:string;today:TripDay;weather:Weather;daysLeft:number;confirmedCount:number;unresolved:string[];nextAction:string;totals:{ARS:number;USD:number};tonight?:Stay;onGo:(t:Tab)=>void;onPlan:()=>void}){if(phase==="memory")return <section className="today-page memory-phase"><div className="today-hero"><p>EL VIAJE QUE VIVIMOS</p><h1>Nueve días<br/><em>para recordar.</em></h1><button onClick={()=>onGo("memories")}>Abrir nuestros recuerdos →</button></div><div className="phase-stats"><article><strong>9</strong><span>días</span></article><article><strong>2.370</strong><span>km previstos</span></article><article><strong>{money(totals.ARS)}</strong><span>ARS registrados</span></article></div></section>;
 if(phase==="planning")return <section className="today-page"><div className="planning-hero"><div><p>LA RIOJA · SAN JUAN · 2026</p><h1>{daysLeft} días<br/><em>para la ruta.</em></h1><span>9 días por La Rioja y San Juan · Datos demostrativos</span></div><div className="moon-orbit">☾</div></div><div className="planning-grid"><article className="readiness-card"><small>ESTADO DEL VIAJE</small><h2>{confirmedCount} alojamientos confirmados</h2><div className="progress"><i style={{width:`${Math.min(100,confirmedCount/5*100)}%`}}/></div><p>{unresolved.length?`Faltan resolver: ${unresolved.join(", ")}.`:"Alojamientos completos."}</p><button onClick={onPlan}>Revisar alojamientos →</button></article><article className="next-card"><small>SIGUIENTE DECISIÓN</small><h2>{nextAction}</h2><p>La aplicación prioriza automáticamente lo que todavía falta cerrar.</p><button onClick={onPlan}>Resolver ahora →</button></article><article className="spend-card"><small>GASTADO HASTA HOY</small><h2>$ {money(totals.ARS)}</h2><p>Más USD {money(totals.USD)} registrados.</p><button onClick={()=>onGo("expenses")}>Ver gastos →</button></article></div><div className="trip-preview"><div><p>PRIMER DÍA</p><h2>Córdoba → Chilecito</h2><span>480 km · 7 horas + paradas</span></div><button onClick={()=>onGo("route")}>Ver la hoja de ruta →</button></div></section>;
 return <section className="today-page travel-phase"><div className="travel-top"><div><p>HOY · {today.date.toUpperCase()}</p><h1>{today.place}</h1><span>{today.detail}</span></div>{weather&&<div className="weather"><strong>{weather.temperature}°</strong><span>{weatherText(weather.code)}<br/>Viento {weather.wind} km/h</span></div>}</div><div className="travel-actions"><a href={directions("Mi ubicación",tonight?.mapsQuery||today.place)} target="_blank">Navegar al próximo destino <b>→</b></a><button onClick={()=>onGo("route")}>Ver agenda de hoy</button><button onClick={()=>onGo("expenses")}>Agregar gasto</button><button onClick={()=>onGo("memories")}>Sacar una foto</button></div><div className="today-agenda"><section><p>PLAN DEL DÍA</p><ol>{today.plan.split("\n").map((x,i)=><li key={i}>{x}</li>)}</ol></section><aside><p>ESTA NOCHE</p><h2>{tonight?.name||today.sleep}</h2>{tonight&&<><span>Check-in {tonight.checkIn}</span><a href={maps(tonight.mapsQuery)} target="_blank">Abrir ubicación →</a></>}</aside></div></section>}
function Food({restaurants,editable,setRestaurants}:{restaurants:Restaurant[];editable:boolean;setRestaurants:(v:Restaurant[]|((x:Restaurant[])=>Restaurant[]))=>void}){return <div className="food-v3">{[...new Set(restaurants.map(r=>r.city))].map(city=><section key={city}><div className="food-title"><h2>{city}</h2><span>{restaurants.filter(r=>r.city===city).length} opciones</span></div><div className="food-list">{restaurants.filter(r=>r.city===city).map(r=><article key={r.id}><div><small>{r.moment}</small><h3>{r.name}</h3><p>{r.style} · {r.note}</p></div><div><a href={maps(r.mapsQuery)} target="_blank">Mapa ↗</a>{r.instagram&&<a href={r.instagram} target="_blank">Instagram ↗</a>}{editable?<select value={r.status} onChange={e=>setRestaurants(v=>v.map(x=>x.id===r.id?{...x,status:e.target.value}:x))}><option>Queremos ir</option><option>Planificado</option><option>Reservado</option><option>Fuimos</option><option>Alternativa</option><option>Descartado</option></select>:<b>{r.status}</b>}</div></article>)}</div></section>)}</div>}
